### PR TITLE
add image size change

### PR DESCRIPTION
**Pull request by slighter12**
delete unused file and add application "change image's size"

### CODE REVIEW

**Comment by slighter12** [comment]
delete unused file and add application "change image's size"

**Comment by slighter12** [comment]
delete unused file and add application "change image's size"

**Comment by slighter12** [comment]
delete unused file and add application "change image's size"

**Comment by wonderchang** [comment]
weight or width? Please re-commit.

**Comment by wonderchang** [comment]
If the image's width was less then 1080px, it should not be enlarged.

**Pull request closed without merging**
